server:
  port: 8080

spring:
  application:
    name: TennisService

  datasource:
    url: jdbc:mysql://localhost:3306/tennis_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ENC(JgZC4T6J9ADJ2lzJz7KSxzSkMA4UirPZA8/8rvCytPvHVJd/+YIIIOl2wRqSM9Y+)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jasypt:
    encryptor:
      password: tennis2025!  # 这里是你用于解密的密钥